Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="content">
  <h3>Add an Engineer</h3>

  <h5>Assign an engineer to this machine: @Html.DisplayFor(model => model.Name)</h5>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select Engineer")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" class="btn btn-primary" />
  }
  <hr />
  <p>@Html.ActionLink("Back to Machine List", "Index")</p>
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="content">
  <h3>Add Machine</h3>

  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @style = "width:250px;" })
    <br>
    @Html.LabelFor(model => model.Description)
    <br>
    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @style = "width:500px;" })
    <br>
    @Html.Label("Assign engineer")
    @Html.DropDownList("EngineerId")
    <br>
    <input type="submit" value="Add Machine" class="btn btn-primary" />
  }
  <hr />
  <p>@Html.ActionLink("Back to Machine List", "Index")</p>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="content">
  <h3>Are you sure you want to delete this machine?</h3>

  @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" class="btn btn-primary" />
  }
  <hr />
  @Html.ActionLink("Back to Machine List", "Index")
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="content">
  <h3>Machine Details</h3>
  <h5>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h5>
  <p>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</p>

  @if(@Model.JoinEntities.Count == 0)
  {
    <p>No engineers licensed for this machine</p>
  }
  else
  {
    <div class="join_style">
      <h6>Engineers licensed to service this machine:</h6>
      <ul>
      @foreach(var join in Model.JoinEntities)
      {
        <li>@join.Engineer.Name</li>
        @using (Html.BeginForm("DeleteEngineer", "Machines"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete" class="btn btn-primary"/>
        }
      }
      </ul>
    </div>
  }
  <hr />
  <p>@Html.ActionLink("Assign Engineer", "AddEngineer", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>
  <p>@Html.ActionLink("Back to Machine List", "Index")</p>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<div class="content">
  <h3>Edit</h3>

  <h5>Edit Information: @Html.DisplayFor(model => model.Name)</h5>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @style = "width:250px;" } })
    <br>
    @Html.LabelFor(model => model.Description)
    <br>
    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @style = "width:500px;" })
    <br>
    <input type="submit" value="Save" class="btn btn-primary" />
  }
  <hr />
  <p>@Html.ActionLink("Back to Machine List", "Index")</p>
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<div class="content">
  <h3>Machines</h3>

  @if (@Model.Count == 0)
  {
    <h5>No machines have been added yet</h5>
  } 

  @foreach (Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId })</li>
  }
  <hr />
  <p>@Html.ActionLink("Add Machine", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>