Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
          .Include(engineer => engineer.JoinEntities)
          .ThenInclude(join => join.Machine)
          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer
<div class="content">
  <h2>Add a Machine</h2>

  <h4>Assign a machine to this engineer: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select Machine")
    @Html.DropDownList("MachineId")
    <br>
    <input type="submit" value="Save" class="btn btn-primary" />
  }
  <hr />
  <p>@Html.ActionLink("Back to Engineer List", "Index")</p>
</div>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="content">
  <h3>Add Engineer</h3>
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @style = "width:250px;" } )
    <br>
    <input type="submit" value="Add" class="btn btn-primary" />
  }
  <hr />
  <p>@Html.ActionLink("Back to Engineer List", "Index")</p>
</div>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="content">
  <h3>Are you sure you want to delete this engineer?</h3>

  @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" class="btn btn-primary" />
  }
  <hr />
  @Html.ActionLink("Back to Engineer List", "Index")
</div>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;
<div class="content">
  <h3>Engineer Details</h3>
  <h5>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h5>
  <br>
  @if(@Model.JoinEntities.Count == 0)
  {
    <p>This engineer has not been assigned to any machines, or is not licesned</p>
  }
  else
  {
    <div class="join_style">
      <h6>Machines licensed to repair:</h6>
      <ul>
      @foreach(var join in Model.JoinEntities)
      {
        <li>@join.Machine.Name</li>
        @using (Html.BeginForm("DeleteMachine", "Engineers"))
        {
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete" class="btn btn-primary btn-sm"/>
        }
        <br>
      }
      </ul>
    </div>
  }
  <hr />
  <p>@Html.ActionLink("Assign Machine", "AddMachine", new { id = Model.EngineerId })</p>
  <p>@Html.ActionLink("Edit Details", "Edit", new { id = Model.EngineerId })</p>
  <p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>
  <p>@Html.ActionLink("Back to Engineer List", "Index")</p>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<div class="content">
  <h3>Edit</h3>

  <h5>Edit Information: @Html.DisplayFor(model => model.Name)</h5>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.EngineerId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @style = "width:250px;" } })
    <br>
    <input type="submit" value="Save" class="btn btn-primary" />
  }
  <hr />
  <p>@Html.ActionLink("Back to Engineer List", "Index")</p>
</div>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<div class="content">
  <h3>Engineers on staff:</h3>

  @if (@Model.Count == 0)
  {
    <h5>No engineers have been added</h5>
  } 

  <ul>
    @foreach(Engineer engineer in Model)
    {
      <li>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId })</li>
    }
  </ul>
  <hr />
  <p>@Html.ActionLink("Add Engineer", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>